build:
  binary: supervisord
  goos:
    - linux
  goarch:
    - amd64
  ldflags: -s -w -X main.commit={{.Commit}} -X main.date={{.Date}}
archive:
  format: binary
snapshot:
  name_template: "{{.Commit}}"
